from tools.patient import get_patient_history
from tools.eligibility import compare_eligibility
from tools.history import get_authorization_history


def generate_letter(patient_id: str):

    patient = get_patient_history(patient_id)
    decision = compare_eligibility(patient_id)
    history = get_authorization_history(patient_id)

    if "error" in patient:
        return patient

    if "error" in decision:
        return decision

    status = decision["status"].upper()
    reasons = "\n".join(decision["reasons"])

    previous_status = "None"

    if "error" not in history:
        previous_status = history["status"]

    return f"""
=========================================
      PRIOR AUTHORIZATION REQUEST
=========================================

Patient Name       : {patient['name']}
Patient ID         : {patient['patient_id']}
Age                : {patient['age']}
Diagnosis          : {patient['diagnosis']}
Requested Procedure: {patient['requested_procedure']}
Insurance Provider : {patient['insurance']}

Authorization Status : {status}

Reasons:
{reasons}

Previous Authorization Status:
{previous_status}

Generated by MediFlow AI
"""