from tools.patient import get_patient_history
from tools.eligibility import compare_eligibility


def generate_letter(patient_id: str, provider_name: str):

    patient = get_patient_history(patient_id)
    decision = compare_eligibility(patient_id, provider_name)

    if "error" in patient:
        return patient

    if "error" in decision:
        return decision

    status = "APPROVED" if decision["approved"] else "DENIED"

    return f"""
=========================================
      PRIOR AUTHORIZATION REQUEST
=========================================

Patient Name : {patient['name']}
Age          : {patient['age']}
Diagnosis    : {patient['diagnosis']}
Insurance    : {provider_name}

Authorization Status : {status}

Reason:
{decision['reason']}

Generated by MediFlow AI
"""